INSERT INTO CATEGORIA (ID, DESCRICAO)
VALUES 
(NEWID(), 'FAMILIA'), 
(NEWID(), 'TRABALHO'),
(NEWID(), 'ESTUDO'),
(NEWID(), 'LAZER'),
(NEWID(), 'OUTROS');

GO

SELECT *
FROM CATEGORIA 
ORDER BY DESCRICAO;
GO